version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/application

    steps:
      - checkout

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - setup_remote_docker:
          version: 19.03.13

      # Download and cache dependencies
      - restore_cache:
          keys:
          - application-{{ checksum "pom.xml" }}

      - save_cache:
          paths:
            - ~/.m2
          key: application-{{ checksum "pom.xml" }}

      # Package into a JAR
      - run: mvn clean package

      # Build docker image
      - run: docker build -t bricefrisco/eccshopdb-backend:$CIRCLE_BUILD_NUM .

      # Push docker image
      - run: docker push bricefrisco/eccshopdb-backend:$CIRCLE_BUILD_NUM
