version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/application

    steps:
      - checkout

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - setup_remote_docker:
          version: 19.03.13

      - restore_cache:
          keys:
          - application-{{ checksum "pom.xml" }}

      - save_cache:
          paths:
            - ~/.m2
          key: application-{{ checksum "pom.xml" }}

      - run:
          name: Package the JAR
          command: mvn clean package

      - run:
          name: Build docker image
          command: docker build -t bricefrisco/eccshopdb-backend:$CIRCLE_BUILD_NUM .

      - run:
          name: Push docker image
          command: docker push bricefrisco/eccshopdb-backend:$CIRCLE_BUILD_NUM

      - add_ssh_keys:
          fingerprints:
            - "cb:60:be:1c:a7:b9:94:36:5c:5f:6b:ad:d0:a8:20:25"

      - run:
          name: Deploy to server
          command: ssh $HOST "/usr/local/sbin/upgrade-docker-image.sh bricefrisco/eccshopdb-backend \$CIRCLE_BUILD_NUM \$DOCKER_ENV_ARGS"
